import {
  DEFAULT_BADGE_SCALE_PERCENT,
  DEFAULT_STACKED_ACCENT_MODE,
  DEFAULT_STACKED_ELEMENT_OFFSET_PX,
  DEFAULT_STACKED_LINE_GAP_PERCENT,
  DEFAULT_STACKED_LINE_HEIGHT_PERCENT,
  DEFAULT_STACKED_LINE_WIDTH_PERCENT,
  DEFAULT_STACKED_SURFACE_OPACITY_PERCENT,
  DEFAULT_STACKED_WIDTH_PERCENT,
  MAX_BADGE_SCALE_PERCENT,
  MAX_GENRE_BADGE_SCALE_PERCENT,
  MAX_PROVIDER_ICON_SCALE_PERCENT,
  MAX_STACKED_ELEMENT_OFFSET_PX,
  MAX_STACKED_SURFACE_OPACITY_PERCENT,
  MAX_STACKED_LINE_GAP_PERCENT,
  MAX_STACKED_LINE_HEIGHT_PERCENT,
  MAX_STACKED_LINE_WIDTH_PERCENT,
  MAX_STACKED_WIDTH_PERCENT,
  MIN_BADGE_SCALE_PERCENT,
  MIN_PROVIDER_ICON_SCALE_PERCENT,
  MIN_STACKED_ELEMENT_OFFSET_PX,
  MIN_STACKED_SURFACE_OPACITY_PERCENT,
  MIN_STACKED_LINE_GAP_PERCENT,
  MIN_STACKED_LINE_HEIGHT_PERCENT,
  MIN_STACKED_LINE_WIDTH_PERCENT,
  MIN_STACKED_WIDTH_PERCENT,
  QUALITY_BADGE_OPTIONS,
  normalizeBadgeScalePercent,
  normalizeGenreBadgeScalePercent,
  normalizeStackedAccentMode,
  normalizeStackedElementOffsetPx,
  normalizeStackedLineGapPercent,
  normalizeStackedLineHeightPercent,
  normalizeStackedLineWidthPercent,
  normalizeStackedSurfaceOpacityPercent,
  normalizeStackedWidthPercent,
} from '@/lib/badgeCustomization';
import { BACKDROP_RATING_LAYOUT_OPTIONS } from '@/lib/backdropLayoutOptions';
import {
  POSTER_RATINGS_MAX_PER_SIDE_MIN,
  POSTER_RATING_LAYOUT_OPTIONS,
} from '@/lib/posterLayoutOptions';
import {
  QUALITY_BADGE_STYLE_OPTIONS,
  RATING_STYLE_OPTIONS,
} from '@/lib/ratingAppearance';
import {
  AGGREGATE_ACCENT_MODE_OPTIONS,
  AGGREGATE_RATING_SOURCE_OPTIONS,
  MAX_AGGREGATE_ACCENT_BAR_OFFSET,
  MIN_AGGREGATE_ACCENT_BAR_OFFSET,
} from '@/lib/ratingPresentation';
import { type RatingPreference } from '@/lib/ratingProviderCatalog';
import { METADATA_TRANSLATION_MODE_OPTIONS } from '@/lib/metadataTranslation';
import {
  GENRE_BADGE_MODE_OPTIONS,
  GENRE_BADGE_POSITION_OPTIONS,
  GENRE_BADGE_STYLE_OPTIONS,
} from '@/lib/genreBadge';
import { SIDE_RATING_POSITION_OPTIONS } from '@/lib/sideRatingPosition';
import {
  DEFAULT_POSTER_EDGE_OFFSET,
  MAX_POSTER_EDGE_OFFSET,
  normalizePosterEdgeOffset,
} from '@/lib/posterEdgeOffset';
import { RATING_VALUE_MODE_OPTIONS } from '@/lib/ratingDisplay';
import {
  BACKDROP_ARTWORK_SOURCE_OPTIONS,
  BACKDROP_IMAGE_TEXT_OPTIONS,
  EPISODE_ID_MODE_OPTIONS,
  GENRE_BADGE_ANIME_GROUPING_OPTIONS,
  LOGO_ARTWORK_SOURCE_OPTIONS,
  POSTER_ARTWORK_SOURCE_OPTIONS,
  POSTER_IMAGE_SIZE_OPTIONS,
  POSTER_IMAGE_TEXT_OPTIONS,
  SAMPLE_GENRE_BADGE_MODE_DEFAULT,
  SUPPORTED_LANGUAGES,
} from '@/lib/configuratorPageOptions';
import { buildConfiguratorPageProps } from '@/lib/configuratorPageProps';
import { normalizeBaseUrl } from '@/lib/uiConfig';
import { useClientOrigin } from '@/lib/useClientOrigin';
import { useConfiguratorActiveWorkspaceSettings } from '@/lib/useConfiguratorActiveWorkspaceSettings';
import { useConfiguratorFeeds } from '@/lib/useConfiguratorFeeds';
import { useConfiguratorOutputs } from '@/lib/useConfiguratorOutputs';
import { useConfiguratorPageChrome } from '@/lib/useConfiguratorPageChrome';
import { useConfiguratorWorkspaceActions } from '@/lib/useConfiguratorWorkspaceActions';
import { useConfiguratorWorkspaceConfigIo } from '@/lib/useConfiguratorWorkspaceConfigIo';
import { useConfiguratorWorkspaceState } from '@/lib/useConfiguratorWorkspaceState';
import { useConfiguratorWorkspaceStorage } from '@/lib/useConfiguratorWorkspaceStorage';
import { useConfiguratorWorkspaceSummary } from '@/lib/useConfiguratorWorkspaceSummary';
import { useConfiguratorWorkspaceUi } from '@/lib/useConfiguratorWorkspaceUi';

type WorkspacePanelId =
  | 'configurator'
  | 'center-view'
  | 'config-string'
  | 'aio-urls'
  | 'addon-proxy'
  | 'current-setup'
  | 'quick-actions';
type WorkspaceSectionId =
  | 'essentials'
  | 'presentation'
  | 'look'
  | 'quality'
  | 'providers'
  | 'quicktune'
  | 'presets';

export function useConfiguratorWorkspaceRuntime() {
  const baseUrl = normalizeBaseUrl(useClientOrigin());
  const workspaceState = useConfiguratorWorkspaceState();
  const {
    activeProviderEditorId,
    aggregateAccentBarOffset,
    aggregateAccentBarVisible,
    aggregateAccentColor,
    aggregateAccentMode,
    aggregateAudienceAccentColor,
    aggregateCriticsAccentColor,
    backdropAggregateRatingSource,
    backdropArtworkSource,
    backdropGenreBadgeAnimeGrouping,
    backdropGenreBadgeMode,
    backdropGenreBadgePosition,
    backdropGenreBadgeScale,
    backdropGenreBadgeStyle,
    backdropImageText,
    backdropQualityBadgePreferences,
    backdropQualityBadgeScale,
    backdropQualityBadgesMax,
    backdropQualityBadgesStyle,
    backdropRatingBadgeScale,
    backdropRatingPreferences,
    backdropRatingPresentation,
    backdropRatingRows,
    backdropRatingStyle,
    backdropRatingsLayout,
    backdropRatingsMax,
    backdropSideRatingsOffset,
    backdropSideRatingsPosition,
    backdropStreamBadges,
    episodeIdMode,
    xrdbKey,
    experienceMode,
    experienceModeDraft,
    fanartKey,
    genrePreviewMode,
    hideAiometadataCredentials,
    lang,
    logoAggregateRatingSource,
    logoArtworkSource,
    logoBackground,
    logoGenreBadgeAnimeGrouping,
    logoGenreBadgeMode,
    logoGenreBadgePosition,
    logoGenreBadgeScale,
    logoGenreBadgeStyle,
    logoQualityBadgePreferences,
    logoQualityBadgeScale,
    logoQualityBadgesMax,
    logoQualityBadgesStyle,
    logoRatingBadgeScale,
    logoRatingPreferences,
    logoRatingPresentation,
    logoRatingRows,
    logoRatingStyle,
    logoRatingsMax,
    mdblistKey,
    mediaId,
    posterAggregateRatingSource,
    posterArtworkSource,
    posterEdgeOffset,
    posterGenreBadgeAnimeGrouping,
    posterGenreBadgeMode,
    posterGenreBadgePosition,
    posterGenreBadgeScale,
    posterGenreBadgeStyle,
    posterIdMode,
    posterImageSize,
    posterImageText,
    posterQualityBadgePreferences,
    posterQualityBadgeScale,
    posterQualityBadgesMax,
    posterQualityBadgesPosition,
    posterQualityBadgesStyle,
    posterRatingBadgeScale,
    posterRatingPreferences,
    posterRatingPresentation,
    posterRatingRows,
    posterRatingStyle,
    posterRatingsLayout,
    posterRatingsMax,
    posterRatingsMaxPerSide,
    posterSideRatingsOffset,
    posterSideRatingsPosition,
    posterStreamBadges,
    previewType,
    proxyCatalogRules,
    proxyDebugMetaTranslation,
    proxyManifestUrl,
    proxyTranslateMeta,
    proxyTranslateMetaMode,
    qualityBadgesSide,
    ratingProviderAppearanceOverrides,
    ratingValueMode,
    selectedPresetId,
    setActiveProviderEditorId,
    setAggregateAccentBarOffset,
    setAggregateAccentBarVisible,
    setAggregateAccentColor,
    setAggregateAccentMode,
    setAggregateAudienceAccentColor,
    setAggregateCriticsAccentColor,
    setBackdropAggregateRatingSource,
    setBackdropArtworkSource,
    setBackdropGenreBadgeAnimeGrouping,
    setBackdropGenreBadgeMode,
    setBackdropGenreBadgePosition,
    setBackdropGenreBadgeScale,
    setBackdropGenreBadgeStyle,
    setBackdropImageText,
    setBackdropQualityBadgePreferences,
    setBackdropQualityBadgeScale,
    setBackdropQualityBadgesMax,
    setBackdropQualityBadgesStyle,
    setBackdropRatingBadgeScale,
    setBackdropRatingPresentation,
    setBackdropRatingRows,
    setBackdropRatingStyle,
    setBackdropRatingsLayout,
    setBackdropRatingsMax,
    setBackdropSideRatingsOffset,
    setBackdropSideRatingsPosition,
    setBackdropStreamBadges,
    setEpisodeIdMode,
    setXrdbKey,
    setExperienceMode,
    setExperienceModeDraft,
    setFanartKey,
    setGenrePreviewMode,
    setHideAiometadataCredentials,
    setLang,
    setLogoAggregateRatingSource,
    setLogoArtworkSource,
    setLogoBackground,
    setLogoGenreBadgeAnimeGrouping,
    setLogoGenreBadgeMode,
    setLogoGenreBadgePosition,
    setLogoGenreBadgeScale,
    setLogoGenreBadgeStyle,
    setLogoQualityBadgePreferences,
    setLogoQualityBadgeScale,
    setLogoQualityBadgesMax,
    setLogoQualityBadgesStyle,
    setLogoRatingBadgeScale,
    setLogoRatingPresentation,
    setLogoRatingRows,
    setLogoRatingStyle,
    setLogoRatingsMax,
    setMdblistKey,
    setMediaId,
    setPosterAggregateRatingSource,
    setPosterArtworkSource,
    setPosterEdgeOffset,
    setPosterGenreBadgeAnimeGrouping,
    setPosterGenreBadgeMode,
    setPosterGenreBadgePosition,
    setPosterGenreBadgeScale,
    setPosterGenreBadgeStyle,
    setPosterIdMode,
    setPosterImageSize,
    setPosterImageText,
    setPosterQualityBadgePreferences,
    setPosterQualityBadgeScale,
    setPosterQualityBadgesMax,
    setPosterQualityBadgesPosition,
    setPosterQualityBadgesStyle,
    setPosterRatingBadgeScale,
    setPosterRatingPresentation,
    setPosterRatingRows,
    setPosterRatingStyle,
    setPosterRatingsLayout,
    setPosterRatingsMax,
    setPosterRatingsMaxPerSide,
    setPosterSideRatingsOffset,
    setPosterSideRatingsPosition,
    setPosterStreamBadges,
    setPreviewType,
    setProxyCatalogRules,
    setProxyDebugMetaTranslation,
    setProxyManifestUrl,
    setProxyTranslateMeta,
    setProxyTranslateMetaMode,
    setQualityBadgesSide,
    setRatingProviderAppearanceOverrides,
    setRatingValueMode,
    setSelectedPresetId,
    setShowConfigString,
    setShowExperienceModal,
    setShowProxyUrl,
    setSimklClientId,
    setStickyPreviewEnabled,
    setThumbnailRatingRows,
    setTmdbIdScope,
    setTmdbKey,
    setWorkspaceCenterView,
    showConfigString,
    showExperienceModal,
    showProxyUrl,
    simklClientId,
    stickyPreviewEnabled,
    thumbnailRatingPreferences,
    tmdbIdScope,
    tmdbKey,
    workspaceCenterView,
  } = workspaceState;

  const feeds = useConfiguratorFeeds();

  const activeWorkspaceSettings = useConfiguratorActiveWorkspaceSettings({
    backdropGenreBadgeAnimeGrouping,
    backdropGenreBadgeMode,
    backdropGenreBadgePosition,
    backdropGenreBadgeScale,
    backdropGenreBadgeStyle,
    backdropQualityBadgePreferences,
    backdropQualityBadgeScale,
    backdropQualityBadgesMax,
    backdropQualityBadgesStyle,
    backdropRatingBadgeScale,
    backdropStreamBadges,
    logoGenreBadgeAnimeGrouping,
    logoGenreBadgeMode,
    logoGenreBadgePosition,
    logoGenreBadgeScale,
    logoGenreBadgeStyle,
    logoQualityBadgePreferences,
    logoQualityBadgeScale,
    logoQualityBadgesMax,
    logoQualityBadgesStyle,
    logoRatingBadgeScale,
    posterGenreBadgeAnimeGrouping,
    posterGenreBadgeMode,
    posterGenreBadgePosition,
    posterGenreBadgeScale,
    posterGenreBadgeStyle,
    posterQualityBadgePreferences,
    posterQualityBadgeScale,
    posterQualityBadgesMax,
    posterQualityBadgesStyle,
    posterRatingBadgeScale,
    posterRatingsLayout,
    posterStreamBadges,
    previewType,
    setBackdropGenreBadgeAnimeGrouping,
    setBackdropGenreBadgeMode,
    setBackdropGenreBadgePosition,
    setBackdropGenreBadgeScale,
    setBackdropGenreBadgeStyle,
    setBackdropQualityBadgePreferences,
    setBackdropQualityBadgeScale,
    setBackdropQualityBadgesMax,
    setBackdropQualityBadgesStyle,
    setBackdropRatingBadgeScale,
    setBackdropStreamBadges,
    setLogoGenreBadgeAnimeGrouping,
    setLogoGenreBadgeMode,
    setLogoGenreBadgePosition,
    setLogoGenreBadgeScale,
    setLogoGenreBadgeStyle,
    setLogoQualityBadgePreferences,
    setLogoQualityBadgeScale,
    setLogoQualityBadgesMax,
    setLogoQualityBadgesStyle,
    setLogoRatingBadgeScale,
    setPosterGenreBadgeAnimeGrouping,
    setPosterGenreBadgeMode,
    setPosterGenreBadgePosition,
    setPosterGenreBadgeScale,
    setPosterGenreBadgeStyle,
    setPosterQualityBadgePreferences,
    setPosterQualityBadgeScale,
    setPosterQualityBadgesMax,
    setPosterQualityBadgesStyle,
    setPosterRatingBadgeScale,
    setPosterStreamBadges,
  });
  const {
    activeGenreBadgeAnimeGrouping,
    activeGenreBadgeMode,
    activeGenreBadgePosition,
    activeGenreBadgeScale,
    activeGenreBadgeStyle,
    activeQualityBadgesMax,
    setActiveQualityBadgePreferences,
  } = activeWorkspaceSettings;

  const pageChrome = useConfiguratorPageChrome({
    initialSupportedLanguages: SUPPORTED_LANGUAGES,
    tmdbKey,
  });

  const workspaceConfigIo = useConfiguratorWorkspaceConfigIo({
    aggregateAccentBarOffset,
    aggregateAccentBarVisible,
    aggregateAccentColor,
    aggregateAccentMode,
    aggregateAudienceAccentColor,
    aggregateCriticsAccentColor,
    backdropAggregateRatingSource,
    backdropArtworkSource,
    backdropGenreBadgeAnimeGrouping,
    backdropGenreBadgeMode,
    backdropGenreBadgePosition,
    backdropGenreBadgeScale,
    backdropGenreBadgeStyle,
    backdropImageText,
    backdropQualityBadgePreferences,
    backdropQualityBadgeScale,
    backdropQualityBadgesStyle,
    backdropQualityBadgesMax,
    backdropRatingBadgeScale,
    backdropRatingPreferences,
    backdropRatingRows,
    backdropRatingPresentation,
    backdropRatingStyle,
    backdropRatingsLayout,
    backdropRatingsMax,
    backdropSideRatingsOffset,
    backdropSideRatingsPosition,
    backdropStreamBadges,
    episodeIdMode,
    xrdbKey,
    fanartKey,
    lang,
    logoAggregateRatingSource,
    logoArtworkSource,
    logoBackground,
    logoGenreBadgeAnimeGrouping,
    logoGenreBadgeMode,
    logoGenreBadgePosition,
    logoGenreBadgeScale,
    logoGenreBadgeStyle,
    logoQualityBadgePreferences,
    logoQualityBadgeScale,
    logoQualityBadgesStyle,
    logoQualityBadgesMax,
    logoRatingBadgeScale,
    logoRatingPreferences,
    logoRatingRows,
    logoRatingPresentation,
    logoRatingStyle,
    logoRatingsMax,
    mdblistKey,
    posterAggregateRatingSource,
    posterArtworkSource,
    posterEdgeOffset,
    posterGenreBadgeAnimeGrouping,
    posterGenreBadgeMode,
    posterGenreBadgePosition,
    posterGenreBadgeScale,
    posterGenreBadgeStyle,
    posterImageSize,
    posterImageText,
    posterQualityBadgePreferences,
    posterQualityBadgeScale,
    posterQualityBadgesPosition,
    posterQualityBadgesStyle,
    posterQualityBadgesMax,
    posterRatingBadgeScale,
    posterRatingPreferences,
    posterRatingRows,
    posterRatingPresentation,
    posterRatingStyle,
    posterRatingsLayout,
    posterRatingsMax,
    posterRatingsMaxPerSide,
    posterSideRatingsOffset,
    posterSideRatingsPosition,
    posterStreamBadges,
    proxyCatalogRules,
    proxyDebugMetaTranslation,
    proxyManifestUrl,
    proxyTranslateMeta,
    proxyTranslateMetaMode,
    qualityBadgesSide,
    ratingProviderAppearanceOverrides,
    ratingValueMode,
    setAggregateAccentBarOffset,
    setAggregateAccentBarVisible,
    setAggregateAccentColor,
    setAggregateAccentMode,
    setAggregateAudienceAccentColor,
    setAggregateCriticsAccentColor,
    setBackdropAggregateRatingSource,
    setBackdropArtworkSource,
    setBackdropGenreBadgeAnimeGrouping,
    setBackdropGenreBadgeMode,
    setBackdropGenreBadgePosition,
    setBackdropGenreBadgeScale,
    setBackdropGenreBadgeStyle,
    setBackdropImageText,
    setBackdropQualityBadgePreferences,
    setBackdropQualityBadgeScale,
    setBackdropQualityBadgesStyle,
    setBackdropQualityBadgesMax,
    setBackdropRatingBadgeScale,
    setBackdropRatingPresentation,
    setBackdropRatingRows,
    setBackdropRatingStyle,
    setBackdropRatingsLayout,
    setBackdropRatingsMax,
    setBackdropSideRatingsOffset,
    setBackdropSideRatingsPosition,
    setBackdropStreamBadges,
    setEpisodeIdMode,
    setXrdbKey,
    setFanartKey,
    setLang,
    setLogoAggregateRatingSource,
    setLogoArtworkSource,
    setLogoBackground,
    setLogoGenreBadgeAnimeGrouping,
    setLogoGenreBadgeMode,
    setLogoGenreBadgePosition,
    setLogoGenreBadgeScale,
    setLogoGenreBadgeStyle,
    setLogoQualityBadgePreferences,
    setLogoQualityBadgeScale,
    setLogoQualityBadgesStyle,
    setLogoQualityBadgesMax,
    setLogoRatingBadgeScale,
    setLogoRatingPresentation,
    setLogoRatingRows,
    setLogoRatingStyle,
    setLogoRatingsMax,
    setMdblistKey,
    setPosterAggregateRatingSource,
    setPosterArtworkSource,
    setPosterEdgeOffset,
    setPosterGenreBadgeAnimeGrouping,
    setPosterGenreBadgeMode,
    setPosterGenreBadgePosition,
    setPosterGenreBadgeScale,
    setPosterGenreBadgeStyle,
    setPosterImageSize,
    setPosterImageText,
    setPosterQualityBadgePreferences,
    setPosterQualityBadgeScale,
    setPosterQualityBadgesPosition,
    setPosterQualityBadgesStyle,
    setPosterQualityBadgesMax,
    setPosterRatingBadgeScale,
    setPosterRatingPresentation,
    setPosterRatingRows,
    setPosterRatingStyle,
    setPosterRatingsLayout,
    setPosterRatingsMax,
    setPosterRatingsMaxPerSide,
    setPosterSideRatingsOffset,
    setPosterSideRatingsPosition,
    setPosterStreamBadges,
    setProxyCatalogRules,
    setProxyDebugMetaTranslation,
    setProxyManifestUrl,
    setProxyTranslateMeta,
    setProxyTranslateMetaMode,
    setQualityBadgesSide,
    setRatingProviderAppearanceOverrides,
    setRatingValueMode,
    setSimklClientId,
    setThumbnailRatingRows,
    setTmdbIdScope,
    setTmdbKey,
    simklClientId,
    thumbnailRatingPreferences,
    tmdbIdScope,
    tmdbKey,
  });
  const { applySavedUiConfig, buildCurrentUiConfig } = workspaceConfigIo;

  const workspaceStorage = useConfiguratorWorkspaceStorage({
    applySavedUiConfig,
    buildCurrentUiConfig,
    stickyPreviewEnabled,
    experienceMode,
    selectedPresetId,
    setStickyPreviewEnabled,
    setExperienceMode,
    setExperienceModeDraft,
    setShowExperienceModal,
    setSelectedPresetId,
  });
  const { applyWorkspaceConfig } = workspaceStorage;

  const workspaceOutputs = useConfiguratorOutputs({
    activeGenreBadgeAnimeGrouping,
    activeGenreBadgeMode,
    activeGenreBadgePosition,
    activeGenreBadgeScale,
    activeGenreBadgeStyle,
    activeQualityBadgesMax,
    aggregateAccentBarOffset,
    aggregateAccentBarVisible,
    aggregateAccentColor,
    aggregateAccentMode,
    aggregateAudienceAccentColor,
    aggregateCriticsAccentColor,
    backdropAggregateRatingSource,
    backdropArtworkSource,
    backdropGenreBadgeAnimeGrouping,
    backdropGenreBadgePosition,
    backdropGenreBadgeScale,
    backdropGenreBadgeStyle,
    backdropImageText,
    backdropQualityBadgePreferences,
    backdropQualityBadgeScale,
    backdropQualityBadgesStyle,
    backdropRatingBadgeScale,
    backdropRatingPreferences,
    backdropRatingPresentation,
    backdropRatingStyle,
    backdropRatingsLayout,
    backdropRatingsMax,
    backdropSideRatingsOffset,
    backdropSideRatingsPosition,
    backdropStreamBadges,
    baseUrl,
    buildCurrentUiConfig,
    episodeIdMode,
    xrdbKey,
    fanartKey,
    genrePreviewMode,
    hideAiometadataCredentials,
    isLatestReleaseLoading: feeds.isLatestReleaseLoading,
    lang,
    latestReleaseTag: feeds.latestReleaseTag,
    logoAggregateRatingSource,
    logoArtworkSource,
    logoBackground,
    logoGenreBadgeAnimeGrouping,
    logoGenreBadgePosition,
    logoGenreBadgeScale,
    logoGenreBadgeStyle,
    logoQualityBadgePreferences,
    logoQualityBadgeScale,
    logoQualityBadgesStyle,
    logoRatingBadgeScale,
    logoRatingPreferences,
    logoRatingPresentation,
    logoRatingStyle,
    logoRatingsMax,
    mdblistKey,
    mediaId,
    pendingReleaseTag: feeds.pendingReleaseTag,
    posterAggregateRatingSource,
    posterArtworkSource,
    posterEdgeOffset,
    posterGenreBadgeAnimeGrouping,
    posterGenreBadgePosition,
    posterGenreBadgeScale,
    posterGenreBadgeStyle,
    posterIdMode,
    posterImageSize,
    posterImageText,
    posterQualityBadgePreferences,
    posterQualityBadgeScale,
    posterQualityBadgesPosition,
    posterQualityBadgesStyle,
    posterRatingBadgeScale,
    posterRatingPreferences,
    posterRatingPresentation,
    posterRatingStyle,
    posterRatingsLayout,
    posterRatingsMax,
    posterRatingsMaxPerSide,
    posterSideRatingsOffset,
    posterSideRatingsPosition,
    posterStreamBadges,
    previewType,
    proxyUrlVisible: showProxyUrl,
    qualityBadgesSide,
    ratingProviderAppearanceOverrides,
    ratingValueMode,
    showConfigString,
    shouldShowQualityBadgesPosition: activeWorkspaceSettings.shouldShowQualityBadgesPosition,
    shouldShowQualityBadgesSide: activeWorkspaceSettings.shouldShowQualityBadgesSide,
    simklClientId,
    tmdbIdScope,
    tmdbKey,
  });
  const { aiometadataCopyBlock, configString, genrePreviewCards, proxyUrl } = workspaceOutputs;

  const workspaceUi = useConfiguratorWorkspaceUi<WorkspacePanelId, WorkspaceSectionId>({
    aiometadataCopyBlock,
    configString,
    experienceModeDraft,
    initialOpenPanels: ['configurator', 'center-view', 'quick-actions'],
    proxyUrl,
    setShowConfigString,
    setShowProxyUrl,
    setExperienceMode,
    setExperienceModeDraft,
    setShowExperienceModal,
    showConfigString,
    showExperienceModal,
    showProxyUrl,
  });
  const { handleContinueExperienceMode, handleExitWizard } = workspaceUi;

  const workspaceActions = useConfiguratorWorkspaceActions({
    applyWorkspaceConfig,
    buildCurrentUiConfig,
    handleExitWizard,
    previewType,
    setActiveQualityBadgePreferences,
    setBackdropRatingRows,
    setLogoRatingRows,
    setPosterRatingRows,
    setRatingProviderAppearanceOverrides,
    setSelectedPresetId,
    setThumbnailRatingRows,
  });

  const workspaceSummary = useConfiguratorWorkspaceSummary({
    activeProviderEditorId,
    aggregateAccentColor,
    aggregateAccentMode,
    aggregateAudienceAccentColor,
    aggregateCriticsAccentColor,
    backdropAggregateRatingSource,
    backdropArtworkSource,
    backdropArtworkSourceOptions: BACKDROP_ARTWORK_SOURCE_OPTIONS,
    backdropImageText,
    backdropImageTextOptions: BACKDROP_IMAGE_TEXT_OPTIONS,
    backdropRatingPresentation,
    backdropRatingRows,
    backdropRatingStyle,
    backdropRatingsLayout,
    backdropSideRatingsOffset,
    backdropSideRatingsPosition,
    configString,
    genrePreviewCards,
    genrePreviewMode,
    logoAggregateRatingSource,
    logoArtworkSource,
    logoArtworkSourceOptions: LOGO_ARTWORK_SOURCE_OPTIONS,
    logoRatingPresentation,
    logoRatingRows,
    logoRatingStyle,
    posterAggregateRatingSource,
    posterArtworkSource,
    posterArtworkSourceOptions: POSTER_ARTWORK_SOURCE_OPTIONS,
    posterImageSize,
    posterImageSizeOptions: POSTER_IMAGE_SIZE_OPTIONS,
    posterImageText,
    posterImageTextOptions: POSTER_IMAGE_TEXT_OPTIONS,
    posterRatingPresentation,
    posterRatingRows,
    posterRatingStyle,
    posterRatingsLayout,
    posterSideRatingsOffset,
    posterSideRatingsPosition,
    previewType,
    proxyUrl,
    selectedPresetId,
    setBackdropAggregateRatingSource,
    setBackdropImageText,
    setBackdropRatingPresentation,
    setBackdropRatingStyle,
    setBackdropSideRatingsOffset,
    setBackdropSideRatingsPosition,
    setLogoAggregateRatingSource,
    setLogoRatingPresentation,
    setLogoRatingStyle,
    setPosterAggregateRatingSource,
    setPosterImageText,
    setPosterRatingPresentation,
    setPosterRatingStyle,
    setPosterSideRatingsOffset,
    setPosterSideRatingsPosition,
    wizardAnswers: workspaceUi.wizardAnswers,
    wizardQuestionIndex: workspaceUi.wizardQuestionIndex,
  });

  const {
    heroProps,
    inputsPanelProps,
    outroProps,
    topNavProps,
    workspaceColumnsProps,
  } = buildConfiguratorPageProps({
    activeWorkspaceSettings,
    baseUrl,
    feeds,
    outputs: workspaceOutputs,
    pageChrome,
    workspaceActions,
    workspaceState,
    workspaceStorage,
    workspaceSummary,
    workspaceUi,
  });

  return {
    experienceModeDraft,
    handleContinueExperienceMode,
    heroProps,
    inputsPanelProps,
    outroProps,
    pageRef: pageChrome.pageRef,
    setExperienceModeDraft,
    showExperienceModal,
    topNavProps,
    workspaceColumnsProps,
  };
}
